[package]
name = "mlir-test"
version = "0.1.0"
edition = "2021"

[dependencies]
llvm-sys = "191.0.0"
melior = "0.20.1"
mlir-sys = "0.4.1"


[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.5"
cmake = "0.1.52"
