[package]
name = "mlir-test"
version = "0.1.0"
edition = "2021"

[dependencies]
melior = { path = "../melior/melior", features = ["ods-dialects"] }
mlir-sys = "0.4.1"


[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.5"
